### ISSUE TITLE
Unhandled error bug and non-html

### ISSUE THREAD

**Issue by kevindeasis** [matthewmueller/x-ray#103]
Using these url they will have errors  that will not get caught and crash node. 

http://cdn.sstatic.net/security/img/apple-touch-icon@2.png?v=497726d850f9&a?v=497726d850f9&a
https://www.csie.ntu.edu.tw/~kmchao/bcc03fall/chap08.ppt

I'm guessing errors will happen with any non-html links and links without html body. Whats a good way to fix or handle these errors?

**Comment by lathropd** [comment]
I’m sorry nobody ever got back to you. Yes, you’d need a selector that avoids requesting a non html page.
