### ISSUE TITLE
how to target .xml pages

### ISSUE THREAD

**Issue by kanethal** [matthewmueller/x-ray#105]
Hello, Been making lots of progress on using x-ray and love it.
I have a new use case that I'm not sure how to proceed on:

I have a directory page with URL links that I can target:
 `http://www.site.com/this-is-what-you-want`

The data I would like to parse through is stored as xml at the address:
`http://www.site.com/this-is-what-you-want.xml`

I'm currently composing my scrape like this for the normal HTML stuff:

``` javascript
var scope = "body"
var targets = {
title: "h1",
otherstuff: "x(a.iwantxml@href, 'div')"
}
x(url, scope, targets)
    .paginate('a.next@href')
    (fn)
```

How can I target the .xml version of the url at `a.iwantxml@href`? Natively that URL is composed as:
`http://www.site.com/this-is-what-you-want`

Assuming I can get the xml content, can I get some tips on using selectors for xml? Can I still use CSS style selectors? Or XPath? Any help would be great

Thanks again for such a great project!

**Comment by monte-hayward** [comment]
You can use CSS element selectors. 
This appears to break down once you have namespaced elements.
E.g., you can select id and title, but not description in the following XML.
```
<feed>
  <entry>
      <id>f001</id>
      <title>On the Plains</title>
      <media:group>
          <media:description>My Video was shot in Mozambique...</media:description>
         ...
```

```
x(feedUrl, 'feed entry', [{
        id: 'id',
        title: 'title',
        description: 'media media\:description'
        
    }])( fn(){})
```

**Comment by kamillo1888** [comment]
@monte-hayward this method is nor working for me - when i am using this selector my return object is undefined.

**Comment by DannyCork** [comment]
Closing, as @kamillo1888 provided a working example and the fact that the original issue is close to 2 years old.

Please open a new issue if this is not resolved.
