### ISSUE TITLE
Is there a way to track the progress of a scrape?

### ISSUE THREAD

**Issue by kanethal** [matthewmueller/x-ray#107]
Hello, currently I am running xray to paginate over 50+ pages, and right now I don't know of a way to log back which url is being fetched. I was wondering if there is a way to console.log the current URL or get feedback on the progress of the scrape? Thanks in advance! Dan.

**Comment by demiro** [comment]
I'd love to have this feature as well

**Comment by Zoddy** [comment]
:+1:

**Comment by gebrits** [comment]
Logging each url being scraped can be done with `DEBUG=x-ray node <yourapp>`

Doing some more involved progress/counting/aggregation is not build in.
However, you could hack something like this which works perfectly for me

Contrived:

``` javascript
var urlsProcessed = 0;

x('https://dribbble.com', 'li.group', [{
  title: '.dribbble-img strong',
  _bogus: function($){
  urlsProcessed++;
  },
}])

//post process results to remove _bogus (or anything starting with _ as I
use it)

//log some stats
(function stats(){
console.log("processed urls", urlsProcessed);
setTimeout(stats, 5000);
}());

```

**Comment by DannyCork** [comment]
@gebrits hack is a usable workaround. If someone wishes to address this please submit a pr. Thanks.
