### ISSUE TITLE
Nested crawling broken on 'master'. When to merge 'bugfix/nested-crawling'

### ISSUE THREAD

**Issue by gebrits** [matthewmueller/x-ray#111]
'bugfix/nested-crawling' seems to fix nested crawling (at a glance) which is broken on 'master' (but works on '2.0.2' 

Is there any intent to merge this branch soonish?

**Comment by GeoffreyEmery** [comment]
+2

**Comment by madibalive** [comment]
yh nested scrawling seem to no work on masster branch , but it is available on the tutorial page or index page

**Comment by OllieJennings** [comment]
How come nested crawling is broken in master? the branch is working but can't seem to get npm to install that dam thing...

**Comment by madibalive** [comment]
hi , it working now apply [] multip selector to the nested crawler , that fix issue before , but i re wired my logic 
and the nested feature is working perfectly now ,

**Comment by andrecassal** [comment]
@madibalive could you give the code you're testing with?
This one doesn't work.
```
...{ 
articles: x('article h1 a@href',[{h:'h1'}]) 
}
```

**Comment by madibalive** [comment]
just a sample here ,
initially didnt return anything ( mostly mean ur selector is broken , re target it ) 
after digging further into the source code , i found the issue 
one more tip, if any of the early setter fail (title, desc,image ......) could also caused the crawler to fail , well not sure if design to behave ,but i faced that issue too.

```javascript
var Xray = require('x-ray');
var x = Xray();
var html = 'http://www.myjoyonline.com/news.php';

x(html, 'ul.opinion-listings li', [{
		title: '.head .title a',
		desc: '.info',
		date: '.head',
		img: 'div.image-inner > a img@src',
		url: '.head .title a@href',
		fullStory: x('.head .title a@href', ['div.side1 div.storypane p'])
	}])
	(function(err, obj) {
		console.log(obj);
		
		}
	});

````
hope this helps

**Comment by OllieJennings** [comment]
@madibalive your code above has a slight syntax error, you have an extra `}` underneath the `console.log` line

**Comment by OllieJennings** [comment]
@andrecassal & @madibalive 

So, the code will exit if it hits a url it can't parse or **resolve** it, therefore we need a way to skip the URL and move onto the next one. Fortunately the current version **2.0.3** does have this implemented.

So if you checkout the branch `bugfix/nested-crawling` and then edit the lines `114` & `115` in the **index.js** to be:

```
114: debug('%s is not a url. Skipping', url);
115: return node.html(load(""), next);
```

then it will continue to parse and resolve everything it can, returning an answer even if some items do not have urls or un-resolvable.

Hope this helps

**Comment by madibalive** [comment]
great thanks for the pointing that out @OllieJennings

**Comment by OllieJennings** [comment]
Not sure if @matthewmueller is on top of fix that should have nested crawling working in master soon? or if you need, l can look into trying to fix it this weekend, then submit a PR?

**Comment by aaakbar** [comment]
@OllieJennings 

Either: clone repo (chechkout the bugfix branch), install x-ray, use `npm link` in your cloned x-ray to create a "global symlink", use `npm link x-ray` in your project to symlink the cloned repo to it and voila.... 

Or: add this line to your dependencies in package.json
```
dependencies: {
...
"x-ray": "git+ssh://github.com/lapwinglabs/x-ray.git#bugfix/nested-crawling",
...
},
...
```

both works fine but I prefer the first method

**Comment by stephengardner** [comment]
This is not fixed on master yet.  I reverted back to `2.0.0` from `2.0.3`.
Caused me some serious headache :( great module though

+1

**Comment by alfonsodg** [comment]
I am working with 2.0.2 right now, as some people mention the 2.0.3 still presents the bug

**Comment by syzer** [comment]
+1

**Comment by gebrits** [comment]
Hi @Kikobeats . As a new commiter, wanted to direct your attention to this issue. Cheers

**Comment by Kikobeats** [comment]
Hello,

The branch `bugfix/nested-crawling` of this repository looks outdated and I'm very out of the context...

Someone can fork it and create a PR? We can move the conversation into the PR for be merged as soon possible.

**Comment by Kikobeats** [comment]
I'm seeing two PR for resolve this:

https://github.com/lapwinglabs/x-ray/issues/130
https://github.com/lapwinglabs/x-ray/issues/129

Now we have a travis build to verify that new PR doesn't break code. Can any interested write a new PR?

**Comment by madibalive** [comment]
this is still broken , but as pointed out by @alfonsodg  v 2.0.2 still works , but 2.2 still not yet , at least with  code i pasted above, it works on these data 
Am using the v 2.2 ,am passing all the link in the crawler on the return `obj` , and 

```
obj.forEach(item, function(){
     x(item.link, scope,selector)(function(err,obj){ item.crawlData = obj})
}
``` 
add lodash map function for better speed ,if you will . let me know if this bad idea as am still noob

**Comment by Muscot** [comment]
Hi,

I run it to this issue, it took me a while to realise that it was a bug. I think it is the same as describe here.
I tried this and it just return a empty object.

 x('http://www.imdb.com/', {
    title: ['title'],
    links: x('.rhs-body .rhs-row', [{
        text: 'a',
        href: 'a@href',
        next_page: x('a@href', {
          title: 'title',
          heading: 'h1'
        })
    }])
})(function(err, obj) {
    console.log(obj);
});

I did spend a couple of hours and I think I fixed it, at least for this case.

**Comment by alexchantastic** [comment]
This still seems to be broken if the nested crawl attempts to form an array of objects. See https://github.com/lapwinglabs/x-ray/issues/189#issuecomment-290957902 for an example.
