### ISSUE TITLE
Duplicate result of selecting td with classname

### ISSUE THREAD

**Issue by klingkie** [matthewmueller/x-ray#115]
I'm try to get data from td with specific classname but the result is just the first one and duplicate.  Here is my code:-

var Xray = require("x-ray");
var xray = new Xray();

xray('http://www.barchart.com/quotes/stocks/$ONE', 'td', [{
    name: '.qname_shad',
    value: '.qval_shad'
}]
)
(function(err, obj) {
    console.dir(obj);
    });

Regards,

**Comment by reedo808** [comment]
<p>I'm still learning to use x-ray efficiently.  The following is what I came up with that might be close to what you're looking for:</p>
<pre>
var Xray = require("x-ray");
var xray = new Xray();

xray('http://www.barchart.com/quotes/stocks/$ONE', 'td', [{
name: xray('.qname_shad', ''),
value: xray('.qval_shad', '')
}]
)(function(err, obj) {
console.dir(obj);
});
</pre>
<p>The result would be:</p>
<pre>
[ { name: 'High', value: '922.33\t\t\t\t\t\t\t\t\t' },
  { name: 'High', value: '922.33\t\t\t\t\t\t\t\t\t' },
  { name: 'High', value: '922.33\t\t\t\t\t\t\t\t\t' },
  { name: 'High' },
  { value: '922.33\t\t\t\t\t\t\t\t\t' },
  { name: 'Low' },
  { value: '913.38\t\t\t\t\t\t\t\t\t' },
  { name: 'Open' },
  { value: '916.59\t\t\t\t\t\t\t\t\t' },
  { name: 'Prev Close' },
  { value: '916.50\t\t\t\t\t\t\t\t\t' },
  { name: '\r\n\t\t\t\t\t\t\t\t\t\t20-Day Average   924.89\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t' },
  { name: '100-Day Average   899.15\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t' },
  { name: 'Trend\r\n\t\t\t\t\t\t\t\t\t\tSpotter' },
  { value: 'Hold\t\t\t\t\t\t\t\t\t' },
  { name: 'Trend Strength' },
  { value: ' \t\t\t\t\t\t\t\t\t' } ]
</pre>

**Comment by klingkie** [comment]
I'm a novice for javascript & node.js world.  However, I think the result should have only 1 { name: 'High', value: '922.33' }.  Here is my code which using 'cheerio' & 'request' to something like the above x-ray code:-

```
// Load the request module
var request = require("request");
var cheerio = require("cheerio");

var url = 'http://www.barchart.com/quotes/stocks/$ONE';
request(url, function(error, response, body) {
	// check for error
	if (error) {
		return console.log('Error:', error);
	}
	
	// check for right status code
	if (response.statusCode !== 200) {
		return console.log('Invalid Status Code: ', response.statusCode);
	}
	
	if (body) {
		// parse data from web page
		var $ = cheerio.load(body);
		$('.qval_shad').each(function(i, e) {
			console.log("> " + i + ": " + $(e).text());
		});
		console.log('----------------------------------');
		$('.qname_shad').each(function(i, e) {
			console.log("> " + i + ": " + $(e).text().trim());
		});
	}
});
```

The result has only 1 High as I've expected.  So I think x-ray should do something wrong.

**Comment by reedo808** [comment]
<p>Ahh I see, you're only looking for one result.  Try this instead:</p>
<pre>
var Xray = require("x-ray");
var xray = new Xray();

xray('http://www.barchart.com/quotes/stocks/$ONE', 'tr', {
name: '.qname_shad',
value: '.qval_shad'
})
(function(err, obj) {
console.dir(obj);
});
</pre>
<p>The result would be:</p>
<pre>
{ name: 'High', value: '922.33\t\t\t\t\t\t\t\t\t' }
</pre>

**Comment by klingkie** [comment]
No, I don't looking for 1 result.  I want all of .qname_shad and .qval_shad pairs.  In fact, I want Open, High, Low, Close price/value on this page.  And I think x-ray will do this task for me as in my first code.  But I got multiple High which should be only 1.  So I think x-ray would be do wrong thing in its algorithm and I should report it as an issue.

I don't know how x-ray works and why I get multiple 'High' in my result which I think it should return only one.

Thanks for your suggestion.

**Comment by heady** [comment]
@klingkie 
The problem with the original question was selecting a class (qname_shad) within a TD that was already selected.  What you should be doing is starting with the TR since the class is on the TD.  It would look something like:
<pre>
xray('http://www.barchart.com/quotes/stocks/$ONE', 'table#main-content div table table tr', [
	{
		name: '.qname_shad',
		value: '.qval_shad'
	}
])
(function(err, obj) {
	console.dir(obj);
});
</pre>

This loops over each TR and finds a .qname_shad and .qval_shad.  However some TR elements have more than one .qname_shad:

```
<tr style="margin-top:5px;">
	<td class="qname_shad">High</td>
	<td align="right" class="qval_shad" style="border-right: 1px solid #FFFFFF;"><strong>920.07</strong></td>
	<td class="qname_shad">Low</td>
	<td align="right" class="qval_shad"><strong>911.27</strong></td>
</tr>
```

And other .qname_shad elements don't have .qval_shad at all:

```
<td colspan="2" class="qname_shad" style="border-right: 1px solid #FFFFFF; padding-right: 5px;">
	<span style="padding: 0; margin: 0;">20-Day Average</span> 
	<span style="float: right"> <strong> 915.62</strong></span>
</td>
```
Therefore x-ray isn't suitable because your selector doesn't fit a pattern.  You could perform subrequests or parse the results in cheerio, but the default methods will not resolve arrays within arrays or inconsistent class naming.  Regardless, this is not an issue with x-ray.
