### ISSUE TITLE
Workaround for paginate when there is js in the href?

### ISSUE THREAD

**Issue by shwaydogg** [matthewmueller/x-ray#122]
The paginate method takes a selector, of course this is fine if the href is a straight link, but if it contains javascript then it won't work.

I'm looking for a way to either add regex or a function to get the paginate method the link it needs.

...Or a confirmation that pagination will just need to be written outside of x-ray in this case.

https://stackoverflow.com/questions/34459567/with-x-ray-is-there-a-workaround-for-paginate-when-there-is-js-in-the-href

**Comment by Ramarti** [comment]
+1 is there a way around this?

**Comment by Kikobeats** [comment]
Using a function solution could be fine!

**Comment by lathropd** [comment]
This may be part of the same issue in https://github.com/matthewmueller/x-ray/issues/54. Merging/closing for now.
