### ISSUE TITLE
Dynamically build follow url

### ISSUE THREAD

**Issue by rahatarmanahmed** [matthewmueller/x-ray#132]
In the example, it shows how we can follow urls to scrape other pages:

``` javascript
x('http://google.com', {
  main: 'title',
  image: x('#gbar a@href', 'title'), // follow link to google images
})
```

But I've come upon a usecase where I need to dynamically build a url from the scraped text. Something like

``` javascript
x('http://google.com', {
  main: 'title',
  // interpolating the selector into the url
  image: x('http://somewhere.com/?query={#some-selector}', 'title')
})
```

I can't tell if there's a way to accomplish this already. I thought about making a custom driver but i don't think xray makes a request unless the scraped text is a url.

**Comment by gebrits** [comment]
I just happened to run into needing this as well, and modified x-ray slightly to allow for this. 

Result is in branch `https://github.com/Kwhen/x-ray/tree/gebrits-patch-1`
This branch contains a number of other fixes/changes that I use myself: **I do not give support, use at own risk**. 

However, the changes to incorporate the 'dynamic url'-functionality is contained in the following commits: 

- https://github.com/lapwinglabs/x-ray/commit/a3d1d544097c3c5986e50844615bcf131330795f
- https://github.com/lapwinglabs/x-ray/commit/d692e04fff4fcea5ad2dada1ef8a9db9d188e09d

So feel free to incorp/apply those in your own version. 

The result is the ability to do something like: 

```javascript

x('http://google.com', {
  main: 'title',
  // interpolating the selector into the url
  image: x(function(el){ //`el` is a cheerio instance which x-ray uses under the hood
    return el.next().find("#some-selector}").attr("href");  //or something like that
  }, 'title')
})

```

**Comment by lathropd** [comment]
Merging this into https://github.com/matthewmueller/x-ray/issues/54
