### ISSUE TITLE
Crawl a web feed by scrolling and waiting for more data to load via ajax

### ISSUE THREAD

**Issue by sauravskumar** [matthewmueller/x-ray#139]
How to crawl a website which has data loaded in the webpage after scrolling(from ajax like facebook feed) and keep on scrolling till we reach the bottom and then in the end collect all the data from the webpage?

**Comment by vinitm** [comment]
Even I am having problems with the above, would love to see it added

**Comment by tribet84** [comment]
+1
Related to #88

**Comment by lathropd** [comment]
This would be done using in with a headless driver ... or just reverse engineering the AJAX and using requests. Closing for now.
