### ISSUE TITLE
HTTP/1.1 999 Request denied

### ISSUE THREAD

**Issue by arturnt** [matthewmueller/x-ray#167]
### Subject of the issue

Certain websites will return `HTTP/1.1 999 Request denied` and this is not flagged as an error in x-ray.
### Your environment
- version of node: 4.2.1
- version of npm: 2.14.7
### Steps to reproduce

Tell us how to reproduce this issue.
### Expected behaviour

Tell us what should happen.
### Actual behaviour

Tell us what happens instead.

**Comment by Kikobeats** [comment]
In general error handle is broken, I'm working on this in `3.x` branch and I hope make a release this month

**Comment by lathropd** [comment]
Closing as merged with #160.
