### ISSUE TITLE
404 & 500 url validation

### ISSUE THREAD

**Issue by JephMarketing** [matthewmueller/x-ray#178]
### Subject of the issue

I am crawling and pulling emails from numerous sites, however, when I add a broken link to my array of urls to crawl I break my script. I am curious if there is anything built in to handle 404 and 505. 
### Your environment

node 4.4.3
npm 2.15.1 (comes with node.js download)
### Expected behaviour

Right now if all links are valid in the import .csv file then it works beautifully, if not I get the following error: 
{ [Error: getaddrinfo ENOTFOUND -------------.com -------------.com:80]
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: '--------.com',
  host: '------------.com',
  port: 80,
  response: undefined }

I am sorry if I missed this in the docs or if it is an easy question, but I really am trying to find a simple and efficient solution. Thanks in advance for your help!

**Comment by lathropd** [comment]
You’ve probably dealt with this another way by now. Sorry we never got back to you. Closing for now as stale. If you have example code you can share, it would still be helpful to see.
