### ISSUE TITLE
Scrape page after its contents are retrieved from server

### ISSUE THREAD

**Issue by diegolaguna** [matthewmueller/x-ray#194]
### Subject of the issue

I'm trying to grab a value from a page, but I need to tell X-Ray to wait until the contents are retrieved from server. Looking at the page's source code, there are tokens like {{selectedBundles.offer.term}}, {{selectedBundles.offer.bundleRackRate}}.
### Your environment
- version of node: v4.2.1
- version of npm: 2.14.7
- version of x-ray: 2.3.0
### Steps to reproduce

var x = Xray();
var url = 'https://www.att.com/shop/u-verse/offer-Details.html?offerId=prod8560739';
var selector = 'div[view-bundle-details="viewBundleDetails"]';
var priceSel = 'span[ng-bind="selectedBundles.offer.bundleRackRate"]';

x(url, selector, priceSel)
(function(err, price){
    console.log('Price: ', price);
});
### Expected behaviour

Price should be 133
### Actual behaviour

got undefined.

**Comment by Ilshidur** [comment]
I think your problem is that some content on the page is altered via some Javascript code. The values you are trying to aggregate are maybe Javascript-generated. I don't know a lot of X-ray, but I think it only retrieves the HTML code and parses it without executing the JS code.

Am I right ?

**Comment by lathropd** [comment]
There is an option to use PhantomJs as a driver.

**Comment by PixelsCommander** [comment]
Not sure why this is closed as there was no definitive solution to the problem.
