### ISSUE TITLE
How to get a variable from a script

### ISSUE THREAD

**Issue by gragra100** [matthewmueller/x-ray#196]
How can i get with x-ray a variable in a script tag ?

For example:
`<script type="text/javascript" charset="utf-8">
        var dataFromServer = [{a:a},{b:b},{c:c},...,{n:n}]
</script>`

I need the variable "dataFromServer", is there a way to retrieve it?

**Comment by bisubus** [comment]
@gragra100 Have you tried to get script contents with `script:not([src]) | someScriptFilter` selector and then parse it in `someScriptFilter` with regexp? Obviously, it won't work if `dataFromServer` is something complex that cannot be fed to `JSON.parse`.

**Comment by DroidNinja** [comment]
How are you able to retrieve it? Any solution?

**Comment by gragra100** [comment]
I used another package, I couldn't do it with x-ray

**Comment by bisubus** [comment]
@DroidNinja As it was mentioned above, you can reach raw DOM within filter functions. I used this hack to overcome some library limitations.

**Comment by lathropd** [comment]
For now, that’s the “correct” answer. Arbitrary JavaScript parsing is its in major thing. This is related to the longstanding issue #6.
