### ISSUE TITLE
Option to return null when empty

### ISSUE THREAD

**Issue by Panthro** [matthewmueller/x-ray#198]
### Subject of the issue

Add an option to return null when empty for schema strict applications
### Expected behaviour

When an element return empty, add the element as a null

Eg:

``` json
{
  "id":"0",
  "name":null
}
```

**Comment by oskarjakiela** [comment]
You can use filters as a workaround

```javascript
var Xray = require('x-ray');
var x = Xray({
  filters: {
    nullify: function(value) { return value ? value : null; }
  }
});

x('https://google.com', {
  empty: 'empty | nullify'
});
```

**Comment by simonseddon** [comment]
Having the same issue myself and tried a filter with no joy. Tried yours out of interest. No such luck. Have you tried this yourself with any luck?

**Comment by lathropd** [comment]
Dupe of #202. Merging.
