### ISSUE TITLE
Selecting multiple tags with the same className?

### ISSUE THREAD

**Issue by austinyearlykim** [matthewmueller/x-ray#215]
Using this syntax:

xray('http://reddit.com', '.theSpecialClass')(fn)

There are multiple items within the website with that specific classname, but it only returns the first one.  Is there a way to grab all of them and maybe I can do a .limit with that return?  I apologize if it's in the documentation, I've read through it twice and it looks like it's not explicitly said anywhere.

Thank you so much for this module, it's so awesome.
Austin

**Comment by gebrits** [comment]
xray('http://reddit.com', ['.theSpecialClass'])(fn)

**Comment by austinyearlykim** [comment]
thank you!
