### ISSUE TITLE
Add delay before reading HTML

### ISSUE THREAD

**Issue by Francisc** [matthewmueller/x-ray#220]
Hello,

Is it possible to add arbitrary delay for when to read the markup?
If there's JS code on the page that's async, it can change the DOM after parser read it.

Is there a way to work around that?

**Comment by hackerunet** [comment]
I'm asking the same myself, and a year later you have no respond yet. really bad!!

**Comment by lathropd** [comment]
If you're using with cheerio, it won't ever run the JavaScript.
