### ISSUE TITLE
How to find redirected URL?

### ISSUE THREAD

**Issue by kdekooter** [matthewmueller/x-ray#224]
In case of redirects is it possible to obtain the URL that x-ray was redirected to?

**Comment by kdgit1** [comment]
Was this resolved?
Update would be helpful. Thanks.

**Comment by DannyCork** [comment]
This functionality doesn't exist. Feel free to contribute a patch to add this :)

**Comment by bfelbo** [comment]
@DannyCork I'm thinking of giving this a go and submitting a PR. If possible, could you provide some high-level guidance on what would be needed to implement this functionality?
