### ISSUE TITLE
Can't get content from <span> tag

### ISSUE THREAD

**Issue by tribet84** [matthewmueller/x-ray#225]
### Subject of the issue

When I want to get the content from a <span> tag x-ray retrieves nothing
### Your environment
- version of node: 4.6.0
- version of npm: 2.15.9
### Steps to reproduce

Go here: https://www.simply.es/compra-online/pescados-y-mariscos.html, and try to get the price of each article with:

```
"use strict";

var Xray = require('x-ray');

var x = Xray({
  filters: {
    whiteSpaces: function (value) {
      return typeof value === 'string' ? value.replace(/ +/g, ' ').replace(/'/g, "''").trim() : value
    }
  }
});
x('https://www.simply.es/compra-online/pescados-y-mariscos.html', '.listing > ul',
  [{
    name: '.descripcionProducto | whiteSpaces',
    price: 'li > span'
  }])(function (err, products) {
    if (err) console.log(err);
    process.exit(0);
  });

```
### Expected behaviour

Return: { name: 'RODABALLO 1-2 KG/PZ.', **price: '11,95 €/Kg' }**
### Actual behaviour

Return: { name: 'RODABALLO 1-2 KG/PZ.' }

**Comment by tribet84** [comment]
Tested on v2.3.1 with the same behaviour.

**Comment by tribet84** [comment]
I found out that if you scrape individually all those items from the individual page description you can get the price. I tried crawling to that page from my main scraping task but didn't work

See code below:
```

var x = Xray({
  filters: {
    cleanPrice: function (value) {
      return typeof value === 'string' ? value.replace(/[^0-9,]/gi, '').trim() : value
    }
  }
});
  x(row.url, '#anade > span | cleanPrice')(function (err, price) {
        if (err) console.error(err);

        var price = parseFloat(price.replace(",", ".")).toFixed(2);

      })
```

**Comment by lathropd** [comment]
Closing as stale. Can reopen if someone wants.
