### ISSUE TITLE
Exclude a tag while scraping

### ISSUE THREAD

**Issue by tokhi** [matthewmueller/x-ray#227]
Can some one help how to build a filter to exclude a  specific `div` while scraping?

``` html
<div class="main">
  <div class="useful">...</div>
  <div class="garbage">..</div>
  ....
</div>
```

In above I want to scrap all the main div(s) except the `garbage` div

**Comment by lathropd** [comment]
You would handle this with the :not pseudo-class: https://developer.mozilla.org/en-US/docs/Web/CSS/:not
