### ISSUE TITLE
Is it possible to have static values in the crawler output?

### ISSUE THREAD

**Issue by talkaboutdesign** [matthewmueller/x-ray#228]
Example Use: 

I am composing a JSON feed as output of the crawler. I want to insert a few values in the output that are just static text. How can this be achieved? 

Current Code:

```
    var stream = x('https://dribbble.com', 'li.group', [{
        title: '.dribbble-img strong',
        link: '.dribbble-link@href',
        image: '.dribbble-img [data-src]@data-src | trim',
    }])
    .paginate('.next_page@href')
    .limit(3)
    .stream();
    stream.pipe(res);
```

I would like to add a static source value to the feed. 

Something like: 

`source: 'Dribbble',`

This part i just want to be static, and not part of the crawler.

**Comment by tribet84** [comment]
+1

**Comment by aamcatamney** [comment]
Possible workaround:

`var x = Xray({
    filters: {
        static: function (value, svalue) {
            return svalue || value;
        }
    }
});

var stream = x('https://dribbble.com', 'li.group', [{
        source: 'title | static:"Dribbble"',
        title: '.dribbble-img strong',
        link: '.dribbble-link@href',
        image: '.dribbble-img [data-src]@data-src | trim',
    }])
    .paginate('.next_page@href')
    .limit(3)
    .stream();
    stream.pipe(res);
`

**Comment by techyrajeev** [comment]
@aamcatamney How to pass a value stored in a variable?
e.g

```
var x="test";
var stream = x('url', 'selector',[{
              res:x,
             img:'.img-selector'
        }])
```

**Comment by aamcatamney** [comment]
@techyrajeev this is untested, but you could try something like this:
`
var x = Xray({
    filters: {
        static: function (value, svalue) {
            return svalue || value;
        }
    }
});
var staticVal = "test";
var stream = x('https://dribbble.com', 'li.group', [{
        source: 'title | static:"' + staticVal +'"',
        title: '.dribbble-img strong',
        link: '.dribbble-link@href',
        image: '.dribbble-img [data-src]@data-src | trim',
    }])
    .paginate('.next_page@href')
    .limit(3)
    .stream();
    stream.pipe(res);
`
