### ISSUE TITLE
is it possible to have keys based on the selector in the output?

### ISSUE THREAD

**Issue by techyrajeev** [matthewmueller/x-ray#235]
### Subject of the issue

Dynamic key in the output

### Environment

* version of node: *v4.4.7*
* version of npm: *3.10.5*

### Steps to reproduce

Basically I am just trying to extract some information and want to set object keys based on the data present in website.

```
      x(html,
          '.parent-group',
              {
                    groups:'.temp-section',
                    '.title':'.detail'
                }
         )
```

But in result I am getting

```
{
    groups:"some value",
   '.title':"some value"
}
```

Not the actual extracted value of `.title`

**Comment by lathropd** [comment]
This can be done by using a .map function on the result later.
