### ISSUE TITLE
Can't select all p tags in body

### ISSUE THREAD

**Issue by tynandebold** [matthewmueller/x-ray#243]
Maybe it's my syntax, but I can't figure out how to return all text within the `p` elements from the body.

My code:
```
var Xray = require('x-ray');
var xray = new Xray();

xray('article url', {
  headline: '.article-headline',
  grafs: xray('body',
    {
      text: ['p']
    })
  }).write('results.json');
```

The result only gives me the text from the first `p` element:
```
{
  "headline": "Senate etc etc.",
  "grafs": {
    "text": [
      "WASHINGTON—Article body here..." 
     ]
  }
}
```

I'm expecting to see the `grafs` object contain as many arrays as there are `p` elements in the body.

Many thanks.

**Comment by lathropd** [comment]
I think you would want the [] around the grafs object not the ‘p’ string. See the example here: https://github.com/matthewmueller/x-ray/blob/master/Readme.md#xraythencb
