### ISSUE TITLE
<Picture /> support

### ISSUE THREAD

**Issue by vedovato** [matthewmueller/x-ray#248]
Is it possible to scrape <picture /> tag where there's multiple <sources /> inside and at attributes like data-*?

**Comment by frank-dspeed** [comment]
@vedovato this is simply using cheerio please look up the documentation of cheerio for that

x-ray is in fact only a request module bundled with cheerio and a other interface for the code:

```
$('Scope can be tag or what ever you like').attr

this x-ray implamentation simply exports a function that places the first values and args to cheerio as Scope selector and find commands.
```

**Comment by vedovato** [comment]
Nice, @frank-dspeed. Thank you
