### ISSUE TITLE
:first, :last :n-child selectors

### ISSUE THREAD

**Issue by deed02392** [matthewmueller/x-ray#256]
### Subject of the issue

When attempting to use the pseudo-selectors to get the n'th child items of nodes, I get the error:

`[SyntaxError: unmatched pseudo-class :last]`

### Your environment

* version of node: *run node --version* v4.6.1
* version of npm: *run npm --version* v2.15.9

### Steps to reproduce

```
x(markup, {
    raw_table: 'table.schedule@html',
    sched_type: ['tr@class'],
    date: ['td.date'],
    descr: ['tr td:last'] // This line
})(
```

### Expected behaviour

`descr `should be a collection of the innerText of all the last columns of all the rows parsed from 'markup'

### Actual behaviour

Syntax error. Exit.

**Comment by kyleoliveiro** [comment]
Shouldn't the selector be `:last-child`?

**Comment by Jacse** [comment]
As @kyleoliveiro mentions the correct selectors are `:first-child`, `:last-child`, `:nth-child`

**Comment by dzcpy** [comment]
Try this:
```
x(markup, {
    raw_table: 'table.schedule@html',
    sched_type: ['tr@class'],
    date: ['td.date'],
    descr: ['tr td:nth-last-child(1)'] // This line
})
```
