### ISSUE TITLE
Crawling SyntaxError: Unmatched selector: @href

### ISSUE THREAD

**Issue by Janghou** [matthewmueller/x-ray#257]
### Subject of the issue

Error while scraping crawled links, doesn't make collection.

### Your environment

* version of node: v6.3.1
* version of npm: 4.2.0
Ubuntu 16.04LTS

### Steps to reproduce
    var Xray = require('x-ray');
     var x = Xray();
    html = '<div> <a href="http://www.google.com">google</a>  <a href="http://www.bing.com"> bing </a> </div>';
    x(html,'a', [{
     engine: x('a'),  
     links: x('a@href', [{href:'a@href',text:'a'}])
    }]).write('result.json');

### Expected behaviour / result
     [ { engine: 'google', links: 
     [{ href: 'http://www.google.com/imghp?tab=wi', text: 'Images' },
     ...
     ]},
     { engine: 'bing', links: 
      [{ href: 'javascript:void(0)' }.
        ...
      ]} ]

### Actual behaviour
`SyntaxError: Unmatched selector: @href`

While without the brackets (array/collection) it does give the first link as result, like above:

         links: x('a@href', {href:'a@href',text:'a'})

Also this works:

       x(html,'a', [{
        engine: x('a'),  
        href: x('a@href', ['a@href']),
        text: x('a@href', ['a']),
       }])

This gives two arrays (href, and text) as result, so you expect that surrounding the original selector with brackets it should return a collection of links.
 
AFAICS, it sets the wrong`scope` on line 218 in index.js. Probably it can't parse the _sub-scope_ at the moment, but it would be nice if it can. 

Any ideas?

**Comment by FezVrasta** [comment]
Had you luck with this?

**Comment by kfkhalili** [comment]
Having this same problem now.

**Comment by dustinschaerer** [comment]
I'm also having the same problem.

**Comment by lathropd** [comment]
Wouldn’t using just ‘a’ as a selector work? a@href isn’t a valid Cheerio selector.

**Comment by michhhh** [comment]
Recently stumbled upon same problem, any potential fixes?

**Comment by lathropd** [comment]
See above: 'a@href' isn't a selector in that use casr. Just use 'a'.
