### ISSUE TITLE
ENOTFOUND - incorrect hostname

### ISSUE THREAD

**Issue by xauxatz** [matthewmueller/x-ray#260]
ENOTFOUND - incorrect hostname

I call xray with the following URL: www.wirdgroup.com
This is a correctly working URL
xray returns with error ENOTFOUND and
- host = "www.wirdgroup.comde"
- hostname = "www.wirdgroup.comde"
- message = getaddrinfo ENOTFOUND www.wirdgroup.comde www.wirdgroup.comde:443

Note the incorrect ending "comde" which obviously is not a correct URL.
My theory is that www.wirdgroup.com refers to www.wirdgroup.com/de and that xray in some way gets confused about this.

### Your environment

I use the newest version of xray with npm in a meteor app.
I run it on Windows 10 (but it gives the same error on Ubuntu)

* version of node: 6.9.3
* version of npm: 4.1.2

### Steps to reproduce

Use xray on the link "www.wirdgroup.com"

### Expected behaviour

The link should be correctly fetched

### Actual behaviour

Tell us what happens instead.

**Comment by DannyCork** [comment]
I used the following code
```
var Xray = require('x-ray');  
var x = Xray();    

x('http://www.wirdgroup.com', 'title')(function(err, result) {
	console.log('error is ' + err);
	console.log('result is ' + result);
})
```

which results in 
```
error is null
result is WIRD AG Zug/Lausanne/Genève/Lugano
```

navigating to https://www.wirdgroup.com/ redirects my browser to 
https://www.wirdgroup.com/en/index.php

I can't reproduce this.

**Comment by lathropd** [comment]
Closing as stale due to nonresponse to Danny.
