### ISSUE TITLE
Null error, but result returns empty string when the classname does indeed exist

### ISSUE THREAD

**Issue by austinyearlykim** [matthewmueller/x-ray#264]
### Subject of the issue
x-ray works for the " 'http://www.google.com', 'title' " example, but xray doesnt detect this classname even though I can see it in the developer console

const xray = require('x-ray')();
xray('http://shop.tcgplayer.com/magic/product/show?ProductName=Jace%2c+the+Mind+Sculptor', '.product__market-price-value')((err, result) => {
console.log(err);
console.log(result);
}) 

Describe your issue here.
err is null and result misses and returns an empty string

### Your environment

* version of node: *run node --version* 7.10.0
* version of npm: *run npm --version* 4.6.1

### Steps to reproduce

Tell us how to reproduce this issue.
Copy and paste above code in node and run.  

### Expected behaviour

Tell us what should happen.
err should be null, results should equal a string dollar amount
### Actual behaviour
err IS null, but results returns an empty string
Tell us what happens instead.

**Comment by DannyCork** [comment]
I'm able to reproduce the issue but only on the site you have detailed.
I've tried other tags and get 
`Request unsuccessful. Incapsula incident ID: xxxxxx-xxxxxxx`
back.

I've tried multiple other sites and they work just fine. I'm guessing that the Incapsula cdn is filtering and rejecting these requests.

**Comment by austinyearlykim** [comment]
Hi @DannyCork.  Thank you for the response.  I've boiled this problem down to the site's Incapsula integration and not a problem with X-Ray.  I'm going to close this thread.
