### ISSUE TITLE
Avoid make two requests to the same URL (cache support?)

### ISSUE THREAD

**Issue by markotom** [matthewmueller/x-ray#265]
I want to avoid make more than one request to the same URL to get properties in depth. This is the use case:

```js
import Xray from 'x-ray'
import * as filters from './filters'

const x = Xray({ filters })

x('http://...', '#content', {
  prop1: 'h1 | clean',
  prop2: x('a@href', '.selector1 | clean'),
  prop3: x('a@href', '.selector2 | clean')
})(function () {
  console.log(...arguments)
})
```

Debug mode displays the following:

```bash
x-ray got response for [FIRST_URL] with status code: 200 +14ms
x-ray got response for [SAME_URL] with status code: 200 +13ms
x-ray got response for [SAME_URL] with status code: 200 +54ms
```

Is it possible? I think that would be a nice feature. What do you think?

Very thanks for this great library!

**Comment by gebrits** [comment]
You can do all of this easily witha  custom driver. No need to adapt x-ray
for that.

**Comment by lathropd** [comment]
Closing based on above response.

Also, adding this behavior would lead to hitting the target site multiple times, which is not good practice.
