### ISSUE TITLE
Add set "charset" for webpage.

### ISSUE THREAD

**Issue by simvolice** [matthewmueller/x-ray#268]
### Subject of the issue

Describe your issue here.

### Your environment

* version of node: *run node --version*
* version of npm: *run npm --version*

### Steps to reproduce

Tell us how to reproduce this issue.

### Expected behaviour

Tell us what should happen.

### Actual behaviour

Tell us what happens instead.

**Comment by m-emelchenkov** [comment]
https://github.com/matthewmueller/x-ray/issues/183

**Comment by lathropd** [comment]
Closing as duplicate of #183
