### ISSUE TITLE
Getting HTMl back from selected elements

### ISSUE THREAD

**Issue by rhclayto** [matthewmueller/x-ray#269]
With Cheerio, it's possible to call .html() to get the HTML corresponding to the cheerio object it's called on. Is something similar possible with x-ray? It's so much easier to traverse the DOM with x-ray, but I need HTML (in order to auto-convert to Markup with another node module). Perhaps this is in the documentation somewhere, but I can't seem to find it if it is. Any help is welcome.

**Comment by lathropd** [comment]
Currently this isn’t implemented, but there is a pending PR to address it.
