### ISSUE TITLE
selecting collections doesn't work in a way specified in docs

### ISSUE THREAD

**Issue by marzelin** [matthewmueller/x-ray#273]
### Subject of the issue

Retrieving collections doesn't work as described in docs

### Your environment

* version of node: 8.5
* version of npm: yarn 1.0.2

reproduction here: https://runkit.com/marzelin/x-ray-bug

given this example:
```js
const x = require("x-ray")()
const html = `
<body>
    <ul>
      <li>1-1</li>
      <li>1-2</li>
      <li>1-3</li>
    </ul>
    <ul>
      <li>2-1</li>
      <li>2-2</li>
      <li>2-3</li>
    </ul>
    <ul>
      <li>3-1</li>
      <li>3-2</li>
      <li>3-3</li>
    </ul>
</body>`

x(html, "body", x("ul", ["li"]))((err, result) => {
    console.log(result)
})
```
per docs `x('ul', ['li'])` should select all items in the first list but it selects all items in all lists.
Also, per docs  `x(['ul'], ['li'])` should return all items in all lists, but it returns nothing.

**Comment by zamrq** [comment]
yeach
selecting collections doesn't work in a way specified in docs

**Comment by JinnaBalu** [comment]
I just replicated above requirement it is working fine able to extract exactly as explained.

![image](https://user-images.githubusercontent.com/11784253/32190787-f7ab0e0a-bdd4-11e7-8b13-714bd8f5e5e3.png)

**Comment by marzelin** [comment]
@JinnaBalu The selector: `x('ul', ['li'])` should only return items from the first list (`["1-1", "1-2", "1-3"]`). The result you've got is all items from all lists. The selector that should return all items from all lists is `x(['ul'], ['li'])`.

**Comment by willisplummer** [comment]
I ran into this issue too 😬

**Comment by lathropd** [comment]
The behavior you want would require you to explicitly to use :nth-of-type(1). By using the array is going to give you all matches.
