### ISSUE TITLE
`x(...).paginate(...).then is not a function` in Meteor-context

### ISSUE THREAD

**Issue by thebarty** [matthewmueller/x-ray#275]
Hi guys,

I am trying to get this working with meteor.

When using `then()` I am getting a `x(...).paginate(...).then is not a function`-error.
This is the code:

```
const Xray = require('x-ray')
const x = Xray()

x('https://www.source.com', '.teilnehmer', [{
  url: '.website .link@href'
}])
.paginate('a@href')
.then(function (res) {
  console.log(res[0]) // prints first result
})
```

Any ideas?

**Comment by eldyvoon** [comment]
same here, somehow it breaks, it used to work.

**Comment by asaldivar** [comment]
https://github.com/matthewmueller/x-ray/issues/278#issuecomment-348391227

Installing the package with the repo clone URI worked for me:

`npm uninstall -S x-ray`
then
`npm i -S https://github.com/matthewmueller/x-ray.git`

**Comment by lathropd** [comment]
Closing this.
