### ISSUE TITLE
Method chaining error with .write() and .then()

### ISSUE THREAD

**Issue by alexadusei** [matthewmueller/x-ray#279]
I looked through the documentation and older issues to see if this was addressed, but doesn't seem to be the case.

The documentation states you can have promise-based behaviour with method-chaining as so:

```javascript
x('https://dribbble.com', 'li.group', [{
  title: '.dribbble-img strong',
  image: '.dribbble-img [data-src]@data-src',
}])
  .paginate('.next_page@href')
  .limit(3)
  .then(function (res) {
    console.log(res[0]) // prints first result
  })
  .catch(function (err) {
    console.log(err) // handle error in promise
  })
```

Looks good, until you add a `.write()` in there, like any other method.

```javascript
x('https://dribbble.com', 'li.group', [{
  title: '.dribbble-img strong',
  image: '.dribbble-img [data-src]@data-src',
}])
  .paginate('.next_page@href')
  .limit(3)
  .write('results.json')
  .then(function (res) {
    console.log(res[0]) // prints first result
  })
  .catch(function (err) {
    console.log(err) // handle error in promise
  })
```

This gives the following error: `TypeError: xray(...).paginate(...).limit(...).write(...).then is not a function`. Any reason why this is?

* version of node: 9.2.0
* version of npm: 5.6.0

**Comment by paulxuca** [comment]
Looks like `.write` returns the write stream, so `.then` won't exist on that.

**Comment by alexadusei** [comment]
That's a shame. Wonder if there'll any workarounds or alternatives, then.

**Comment by paulxuca** [comment]
You can turn the stream into a promise by resolving on the `done` event and rejecting on `error`, which makes it possible to chain promises.

**Comment by alexadusei** [comment]
Good suggestions - thanks @paulxuca!
