### ISSUE TITLE
get a value inside a function

### ISSUE THREAD

**Issue by bassemAmous** [matthewmueller/x-ray#300]
### Subject of the issue

Describe your issue here.

### Your environment

* version of node: *run node --version*
* version of npm: *run npm --version*

### Steps to reproduce

Tell us how to reproduce this issue.

### Expected behaviour

Tell us what should happen.

### Actual behaviour

Tell us what happens instead.

**Comment by bassemAmous** [comment]
I am developing Node Js application using get-proxylist library so my question is how to get the value which is inside the function here is my code:
```

var proxylist = require('get-proxylist');
var array =[]
 proxylist(function(error, result){

        for(var i = 0; i < result.length; i++) {
            array.push(result[i]);
        }
    })
console.log(array[0]) 
```

**Comment by lathropd** [comment]
Not sure what this is requesting. Closing for now.
