### ISSUE TITLE
Scrapping + crawling is not synchronus

### ISSUE THREAD

**Issue by juanpablo64** [matthewmueller/x-ray#306]
### Subject of the issue

When I scrape a  collection of results, I want it to start crawling to the next page after it finishes scraping all the current data. However, I find that when it executes, crawling happens before showing scrapped data

### Your environment

version of node:  v6.11.0
version of npm: v3.10.10

### Steps to reproduce

function scrapeAndCrawl(searchUrl) {

	if (!searchUrl){
		formData.splice(0,1);
		startSearch();

**Comment by lathropd** [comment]
Calling .concurrency(1) should do this. See https://github.com/matthewmueller/x-ray/blob/master/Readme.md#xrayconcurrencyn
