### ISSUE TITLE
isUrl module breaks nesting

### ISSUE THREAD

**Issue by evilive3000** [matthewmueller/x-ray#308]
because of this [issue](https://github.com/segmentio/is-url/issues/19) nested selections does not work.

**Comment by davisjam** [comment]
I just opened a PR on that issue.

**Comment by davisjam** [comment]
New version should be available today or tomorrow, monitor [this PR](https://github.com/segmentio/is-url/pull/20).

**Comment by Raidus** [comment]
Having a similar problem. is-url version 1.3.2 causes some problems with html as input:

```javascript
x(html, '.s-result-item.celwidget', ...
```

Error:
```
TypeError: string.match is not a function
    at isUrl (...node_modules/is-url/index.js:27:22)
```

With is-url version 1.2.2 there are no problems.

**Comment by davisjam** [comment]
Please try with version 1.2.4, just published to npm. If you have any issues, open one against the `is-url` project.

**Comment by Raidus** [comment]
thanks @davisjam! updating to version 1.2.4 resolved the issue.
