### ISSUE TITLE
Selecting all the elements of a html

### ISSUE THREAD

**Issue by iCrackk** [matthewmueller/x-ray#309]
So I want to select all the 'p span' element of the html that looks similar to this:
<div>
      <p><span>This is the first one</span></p>
      <p><span>This is the second one</span></p>
      <p><span>This is the third one</span></p>
</div>

and this is what my code looks like:
const xray = require('x-ray');
const x = xray();

x(url,'p span')(function(err,product){
    if(err == null) console.log(product);
    else console.log(err);
})

but the problem is that it only displays the first element that is this:
"This is the first one"

So is there anything that I'm missing? I want to select and display all of the 'p span' elements in this case it would look like:
      <p><span>This is the first one</span></p>
      <p><span>This is the second one</span></p>
      <p><span>This is the third one</span></p>

Any help would be much appreciated.

**Comment by levibuzolic** [comment]
Please read the documentation about collections. This should get things working:

```js
x(url, {
  products: ['p span']
})(function(err, data){
  if(err == null) console.log(data);
  else console.log(err);
})
```
