### ISSUE TITLE
NPM audit to fix

### ISSUE THREAD

**Issue by gallofeliz** [matthewmueller/x-ray#316]
### Subject of the issue

Hi, npm audit alerts me about vulnerabilities. We need to fix debug and cheerio (for x-ray-crawler) dependencies.

### Your environment

* version of node: *9.4.0*
* version of npm: *6.2.0*

### Steps to reproduce

`npm audit`

### Expected behaviour

Should not throw alerts

### Actual behaviour

Throws 2 alerts

**Comment by fadavi** [comment]
Any solution/workaround for this issue?

**Comment by lathropd** [comment]
We need to bump the debug versions in both x-ray and x-ray-crawler. 

An attempt to address this was made in https://github.com/matthewmueller/x-ray/pull/321/commits, but it doesn't pass CI.

**Comment by SProst** [comment]
@lathropd It looks like it did pass Node version 11.1.0. It failed on the other versions of Node. Depending on whether the upgrade to the library broke backward compatibility, it might be necessary to evaluate the feasibility of dropping support for older versions of Node (<= Node 5).

**Comment by lathropd** [comment]
I think you’re right. Our dependencies seem to be causing those failures all over the place.

@matthewwmueller, any objection to moving minimum to Node 6 (currently in LTS  status) to keep our CI tests working?

**Comment by lathropd** [comment]
Fixed by https://github.com/matthewmueller/x-ray/tree/2.3.4
