### ISSUE TITLE
allowing to select n-th occurence

### ISSUE THREAD

**Issue by gebrits** [matthewmueller/x-ray#32]
I need the following horrible selector to parse some late nineties html:  `.nestedTable[1] tr[0] td[1]`. This doesn't seem to work currently. Is that correct? 

If there's a need (beyond my own) I could try to get this in. It shouldn't be too hard, since I'm pretty sure cheerio already support this, which we can piggy-back on? 

Any pointers appreciated.

**Comment by bogini** [comment]
Check out the [`:nth-of-type`]( https://css-tricks.com/almanac/selectors/n/nth-of-type/) selector.
