### ISSUE TITLE
How to scrap a tag of class="" and how to apply condition on selector that scrap meta tag which has property="og:image"

### ISSUE THREAD

**Issue by AbdulBsit** [matthewmueller/x-ray#320]
### How to scrap a tag of class="" and how to apply condition on selector that scrap meta tag which has property="og:image"

 I want to scrap urls having class="" and then want to scrap meta tags having property of og:image 
how can i filter my result as above

**Comment by lathropd** [comment]
Duplicate of https://github.com/matthewmueller/x-ray/issues/319
