### ISSUE TITLE
Pagination not working seems like i am looping on same page with for number provided in limit(n)

### ISSUE THREAD

**Issue by mustafashaikh4714** [matthewmueller/x-ray#329]
### xray pagination not working

I have this next page link <a class="next" href="">Next</a>. Seems like im looping on same page
i wrote paginate as 
.paginate(' .next a@href ')
.limit(2)
same data display 2 times

### 

* version of node: *run node --version*
* version of npm: *run npm --version*

### Steps to reproduce

Tell us how to reproduce this issue.

### Expected behaviour

Tell us what should happen.

### Actual behaviour

Tell us what happens instead.

**Comment by lathropd** [comment]
It would be helpful to know the page you’re scraping and see the full call... Otherwise it’s hard to know. My first guess is that the selector may be slightly off.
