### ISSUE TITLE
How to close popup window? 

### ISSUE THREAD

**Issue by bosna387** [matthewmueller/x-ray#352]
### Subject of the issue

How would I close a popup window which opens the first time page is accessed? This prevents x-ray to scrape.

### Your environment

* version of node: *run node --version*
* version of npm: *run npm --version*

### Steps to reproduce

Tell us how to reproduce this issue.

### Expected behaviour

Tell us what should happen.

### Actual behaviour

Tell us what happens instead.

**Comment by lathropd** [comment]
Please provide the site info. This isn't enough to reproduce.
