### ISSUE TITLE
Funding for x-ray

### ISSUE THREAD

**Issue by chrisvxd** [matthewmueller/x-ray#363]
Hey @matthewmueller! 👋

Just wanted to reach out about funding your work on x-ray.

@transitive-bullshit and I are both open source maintainers, and we're currently exploring new ways to make OSS funding a viable source of income.

We're currently looking at building SaaS APIs on top of existing OSS libraries, reserving the majority of profits for the original authors. [We've built a few](https://saasify.sh/#/showcase) at this point, but want to keep adding more.

x-ray has a really simple API, so I think it'd be a great fit. I'd love to build a SaaS API on top of it.

Looking forward to hearing your thoughts! 🙏

**Comment by matthewmueller** [comment]
Worth a try! Let me know if you need anything from me.
