### ISSUE TITLE
comments selector (<!-- -->)

### ISSUE THREAD

**Issue by LukaszWiktor** [matthewmueller/x-ray#42]
Is there a way to extract comments from a page source? I mean a content placed between `<!--` and `-->`.

**Comment by matthewmueller** [comment]
Not yet, accepting PRs!

**Comment by brackmayhall** [comment]
+1

**Comment by lathropd** [comment]
I think this would need to be added to Cheerio. In many case you can get it as part of the .html of a parent then use regexes in post-processing. Closing for now.
