### ISSUE TITLE
Add promise support

### ISSUE THREAD

**Issue by monolithed** [matthewmueller/x-ray#62]
``` js
import Xray from 'x-ray';

let scraper = Xray();

scraper(url, {
    items: scraper('.scope', [
        {
            link: '.link@href'
        }
    ])
})
.then(
     result => {
        // All done
     },
     error => {
        // There're errors
     }
});
```

**Comment by matthewmueller** [comment]
yah +1, this should be pretty easy to add

**Comment by kengz** [comment]
I made an attempt while wrapping x-ray for my mini-library, this might help if you can't wait for the new release:

```
function scrape(url, scope, selector) {
    var defer = q.defer();
    x(url, scope, selector)(function(err, res){
        defer.resolve(res);
    })
    return defer.promise;
}
```

Of course by no means it's complete. I didn't need the `err` so I ignored it.

**Comment by jamiehutber** [comment]
+1 to this

**Comment by jamiehutber** [comment]
+1 to this

**Comment by l4u** [comment]
With bluebird, it's a one-liner.
```js
var getTitle = Promise.promisify(x('http://google.com', 'title'));
```

Full example
```js
var Promise = require('bluebird');
var Xray = require('x-ray');
var x = Xray();
var getTitle = Promise.promisify(x('http://google.com', 'title'));
getTitle().then(function(title) {
    console.log(title);  // Google
});
```

**Comment by yang-wei** [comment]
is anyone implementing this?

**Comment by kengz** [comment]
@yang-wei Bluebird is the way to go - the most elegant and easier solution. @monolithed do you wanna mark this as resolved?

**Comment by monolithed** [comment]
@kengz, I use a simple wrapper like:

```js
import Xray from 'x-ray';

export default class {
	get (url, data) {
		return Promise((resolve, reject) => {
			let xray = Xray();

			xray(url, data)((error, result) => {
				if (error) {
					reject(error);
				}
				else {
					resolve(result);
				}
			});
	    });
	}
};

import Xray from './xray';

let xray = new Xray;

xray(url, data).then(result => { });
```

But, the issue is not resolved yet.

**Comment by itzjonas** [comment]
+1

**Comment by marciovicente** [comment]
:+1:

**Comment by kengz** [comment]
Actually made a package months ago for this by extending my answer above. Just putting this out there:
[reqscraper](https://github.com/kengz/reqscraper)

**Comment by monolithed** [comment]
@kengz, I'm sorry, but you package does not any sense for the current issue.

**Comment by tomalex0** [comment]
In current setup, can we use  promise without adding `bluebird`?

I'm looking to get image dimension using https://github.com/nodeca/probe-image-size
how can i chain it using `x-ray` and `promise`

```
        var url  =  'https://www.npmjs.com/';
        x(url, {
            page_title : 'title',
            'page_images' : x('img', [{
                src: '@src',
                height: '@height',
                width: '@width'
            }]),
            metatags_name: x('meta', [{
                name: '@name',
                description: '@content'
            }]),
            metatags_property: x('meta', [{
                name: '@property',
                description: '@content'
            }])
        })(function (err, obj) {             
            res.json(obj);
        });
```

**Comment by obsidience** [comment]
To add to monolithed's answer, I'm using the following:

```
"use strict";

var xray = (require('x-ray'))();

module.exports.Xray = class {
	nestedGet (scope, selector) {
			return xray(scope, selector);
	};
    get (url, scope, selector) {
        return new Promise((resolve, reject) => {
            xray(url, scope, selector)((error, result) => {
                if (error) {
					debugger;
                    reject(error);
                }
                else {
                    resolve(result);
                }
            });
        });
    };
};
```

Usage:

```
"use strict";

var x = new (require('./xray.js')).Xray()
x.get("http://domain.com", "table tr[valign='middle']", [{dateAndTime: 'td:nth-child(1)', links: x.nestedGet('a', [{name: '', link: '@href'}])}])
	.then((result) => {
		debugger;
	});

```

I'm not a guru, so feedback welcomed.

**Comment by Kikobeats** [comment]
Code example looks goods, but I think that promise is not a feature for this library.

You can use [pify](https://github.com/sindresorhus/pify#pify-) out of the box. It converts callback style into Promise style.

**Comment by monolithed** [comment]
Promise is not a feature. It should be a part of any library ))

**Comment by Kikobeats** [comment]
Very related with https://github.com/caolan/async/issues/956.

@monolithed ideally yes, but I feel that first we need to put effort have a better codebase for do it. I'm trying to uncouple some methods that are not related with x-ray interface. Later, we can a promise wrapping around the API methods

**Comment by ivawzh** [comment]
I made a util for xray-to-promise:

```
export function xToPromise(xQuery) {
  return new Promise((resolve, reject) => {
    xQuery((err, results) => {
      if (err) {
        reject(err)
      } else {
        resolve(results)
      }
    })
  })
}

function fetchPage(page) {
  const query = x(page, 'title')
  xToPromise(query).then(
    data => {
      console.log(data)
    },
    err => {
      console.log(err)
    }
  )
}
```

**Comment by ronenteva** [comment]
+1

**Comment by matthewmueller** [comment]
^ you just emailed 13 people. please use the thumbs up button instead

**Comment by kengz** [comment]
New solution that works much better with `xray`'s chainable functions:

*Note that external dependencies are used, so you need to do `npm install --save bluebird lodash stream-to-string*

```js
const Promise = require('bluebird')
const _ = require('lodash')
const sts = require('stream-to-string')
const Xray = require('x-ray')


function streamToPromise(stream) {
  return new Promise((resolve, reject) => {
    sts(stream, (err, res) => {
      if (err) {
        reject(err)
      } else {
        resolve(res)
      }
    })
  })
}

// inject a promisify function to xray using its stream()
// called xray().promisify() to return a promise
function injectWithPromisify(xray) {
  const wrapx = _.wrap(xray, (fn, urlStr, scope, selector) => {
    const initx = fn(urlStr, scope, selector)
    const promisify = function pfn() {
      return streamToPromise(initx.stream())
    }
    _.assign(initx, { promisify })
    return initx
  })
  return wrapx
}

// return a new instance of xray with options
function newXray(){
  let xray = Xray()
  xray = injectWithPromisify(xray)
  return xray
}

// Usage
const xray = newXray()
const url = 'http://www.imdb.com/'
const selector = ['title']

xray(url, selector).promisify()
  .then((res) => {
    console.log(JSON.stringify(res))
  }).catch((err) => {
    console.log(err)
  })
```

What it does is adding a `promisify` function to the `xray(...)` instance, while preserving the others. When executed, the `promisify()` will internally call `xray().stream()` and pipe that to a promise, which is returned.
Since this only injects a new `promisify` function to the original `xray()` instance, one can chain functions as usual before calling `promisify()`:

```js
xray(url, selector)
  .paginate('.next_page@href')
  .limit(3)
  .promisify()
  .then((res) => {
    console.log(JSON.stringify(res))
  }).catch((err) => {
    console.log(err)
  })
```

**Comment by matthewmueller** [comment]
nice! fwiw, I'd totally accept a PR that does something like this:

```js
Xray.prototype.then = function () {
  return new Promise(function (resolve, reject) {
     // ...
  })
}
```

**Comment by kengz** [comment]
@matthewmueller yep, turns out to be way cleaner if done from within the source code. Please review, and advice on some of the unchecked items in the PR

**Comment by viniciusCamargo** [comment]
Heys, guys!

Let me share what I've been doing for a while now, maybe it could help someone (similar to the solution by @monolithed).
Please, keep in mind that I'm not totally sure if it was the best approach for the task, nor if is performant or compliant to best practices. That said, I must say that it's been working really well for me since I haven't seen any issues so far.

```js
const Xray = require('x-ray')

const request = (params) => {
  const { url, filters, limit } = params
  const { parent, children, pagination } = params.selectors

  const x = filters ? Xray({ filters }) : Xray()

  return new Promise((resolve, reject) => {
    try {
      x(url, parent, children)
      ((error, results) => {
        if (error) reject(error)

        resolve(results)
      }).paginate(pagination).limit(limit)
    } catch (error) {
      reject(error)   
    }
  })
}

module.exports = request
```

Then I'd just pass an object like this:
```js
const obj = {
  url,
  filters,
  selectors: {
    parent,
    children,
    pagination
  },
  limit
}

request(obj)
  .then(console.log)
```

Let me know if you'd have any idea on how to improve it. :)

**Comment by gebrits** [comment]
`if (error) reject(error)` -> `if (error) return reject(error)`.
Other than that, that seems like how I would promisify it.

**Comment by gnesher** [comment]
Hi guys,
Is there still an active plan of adding promise support for the queue / priorityQueue? This has been open for a good while
