### ISSUE TITLE
Early exit of pagination if condition met

### ISSUE THREAD

**Issue by doesdev** [matthewmueller/x-ray#73]
It would be ideal to be able to halt pagination if the nth page returns a data set that has already been scraped. Initially I implemented a variation of this idea in Pull Request #72, but that isn't quite right for a couple reasons. 

The biggest issue is the fact that most use cases would include checking a datastore for existence of a scraped record which will nearly always be an asynchronous operation. I've been trying to come up with a way of implementing this in an async way without majorly disrupting / changing the current code.

If you have any ideas on how this might elegantly be implemented I can work on a pull request.

**Comment by ksidpen** [comment]
:+1:

**Comment by lathropd** [comment]
This has been implemented as .abort
