### ISSUE TITLE
Trouble with Pagination

### ISSUE THREAD

**Issue by cookavich** [matthewmueller/x-ray#77]
Noob here needing some help with a little learning project.

I'm trying to grab some info from Craigslist, and I've been able to grab things like the title, price, and url, but I've been having trouble grabbing the images. So, my solution was to use pagination in order to go into each listing where it's easier to get the images (is that even possible?), and also as a bonus I can grab the listing description, as well.

My problem is that I can't seem to figure out how to do that. Like I said, I'm a noob so it's been a learning process even to figure out how to use a library like this for scraping.

Here's what I've got that works:

```
var Xray = require('x-ray');  

var x = Xray();
var url = 'https://louisville.craigslist.org/search/sss?query=stools';

// Grabs data off of Craigslist and then stores it in a JSON file
var jsonList = x(url, {
            stools: x('span.txt', [{
                title: 'a.hdrlnk',
                price: 'span.price',
                link: 'a.hdrlnk @href',
            }]),        
    }).write('./public/all-links.json');
```

Here's what I've got that doesn't work:

```
var posting = x(url, 'section.userbody', {
        post: ['section#postingbody']
})
    .paginate('span.pl', '@href')
    .write('post.json');
```

Any help is appreciated.

**Comment by matthewmueller** [comment]
hm, paginate expects an attribute selector. so without seeing the HTML, you'd probably want to do something like:

```js
.paginate('span.pl a@href')
```

**Comment by bdentino** [comment]
sounds like you're thinking about paginate wrong. Paginate is useful when a website has maybe 200 items in a list but only shows you 50 at a time. You provide the selector that takes you to the page with the next 50 results, and x-ray will pull all of them. 

I think what you want to do is something like this:
```
var jsonList = x(url, {
            stools: x('span.txt', [{
                title: 'a.hdrlnk',
                price: 'span.price',
                link: 'a.hdrlnk @href',
                images: x('a.hdrlnk@href', ['.image-selector@src'])
            }]),        
    }).write('./public/all-links.json');
```

The idea is that the nested `x(..)` call under `images:` will scrape the url resolved by `a.hdrlnk@href` and return the `src` attributes for elements on that page with class `.image-selector`

**Comment by cookavich** [comment]
Mmhmm, @bdentino, I'm just having trouble selecting the img@src on the search page for some reason (the images aren't under the same parent element as the title, price, and link). Even when I try to grab all the img@src from the page all I get is two links to this: "https://www.craigslist.org/images/animated-spinny.gif." 

I'm guessing that means that I'm making too many requests at one time, but I'm not sure

**Comment by bdentino** [comment]
it could also mean that the images you want are being fetched after the page loads via client-side javascript, which won't run unless you're using a headless browser (look at the the x-ray-phantom driver)

**Comment by VPlatoon** [comment]
I am new to x-ray. Where does this `span.txt` come from? Thanks!
