### ISSUE TITLE
Any way to scrape an infinite-scroll page?

### ISSUE THREAD

**Issue by 37** [matthewmueller/x-ray#88]
I've been having trouble trying to scrape a page that loads elements when scrolled, using x-ray-phantom for node. 

I looked through the old documentation for x-ray-phantom and noticed it used to support nightmare's scrollTo method, though I can't find any documentation or examples of this; do you guys have any suggestions?

Thanks!

**Comment by tribet84** [comment]
+1

**Comment by tribet84** [comment]
I managed to scroll an infinite-scroll page using the phantom driver.

I followed the example from the [docs ](https://github.com/lapwinglabs/x-ray-phantom/blob/master/test/phantom.js) but there's lot of room for improvement. 

Any suggestions?

```
"use strict";

var Xray = require('x-ray');
var phantom = require('x-ray-phantom');

var phantom_opts = {
    webSecurity: false,
    images: false,
    weak: false
};

var x = Xray().driver(phantom(phantom_opts, function (nightmare, done) {
    done
        .useragent("Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.111 Safari/537.36")
        .goto(nightmare.request.req.url)
        .scrollTo(4000, 0)
        .wait()
        .scrollTo(8000, 0)
        .wait()
        .scrollTo(12000, 0)
        .wait()
}));



x('https://.../', '.product_list li',
    [{
        name: '.description_1',
        unitPrice: '.description_2',
        image: '.image_line img@src',
        price: '.product_price_cont p',
        url: '.image_line a@href',
        volumen: '.description_1',
        medida: '.description_1'
    }])(function (err, products) {
        if (err) console.log(err);

        console.log(products.length);

        process.exit(0);
    });
```

**Comment by hackerunet** [comment]
This procedure needs access to the host to be able to install stuff like xvfb, how can I delay the respond and start scraping just after all content has been received and js elements are loaded without depending on a display like nightmare and phantom does???

**Comment by lathropd** [comment]
See #139 for more.

**Comment by ukhanzada-nisum-com** [comment]
Does anyone solved this.. I also came across the same problem.

@tribet84 I have tried your solution but it's not working in my case.. it only scraps the first page.

**Comment by tribet84** [comment]
> Does anyone solved this.. I also came across the same problem.
> 
> @tribet84 I have tried your solution but it's not working in my case.. it only scraps the first page.

this is a bit old, prob worth trying cypress, it has scrollto() built in feature https://docs.cypress.io/api/commands/scrollTo

**Comment by ukhanzada-nisum-com** [comment]
Is cypress used for scraping as well?
