### ISSUE TITLE
Stream Newline Delimited JSON

### ISSUE THREAD

**Issue by colinskow** [matthewmueller/x-ray#93]
I am working on a paginated project, and am piping the data into [RXJS](https://github.com/Reactive-Extensions/RxJS) to parse it, filter it, and save it to a database as the project runs. The problem is that if I try to parse the JSON before the entire project is complete, then `JSON.parse` throws a `[TypeError] unexpected end of input`.

I've managed to make it work using the following hack:

``` js
var source = Rx.Node.fromStream(xrayStream)
  .map(function(buff) {
    var buffTxt = buff.toString().trim();
    if(buffTxt.charAt(0) !== '[') buffTxt = '[' + buffTxt;
    if(buffTxt.charAt(buffTxt.length-1) === ',') buffTxt = buffTxt.slice(0,-1);
    if(buffTxt.charAt(buffTxt.length-1) !== ']') buffTxt = buffTxt + ']';
    return JSON.parse(buffTxt.toString());
  })
```

A far better solution would be to stream [Newline Delimited JSON](http://jsonlines.org). This way each chunk of data would be a valid JSON object and I could parse it reliably without hacking it.

**Comment by lathropd** [comment]
Closing for now.
