### ISSUE TITLE
Errors downstream of .write() are being squelched

### ISSUE THREAD

**Issue by KodeAndGame** [matthewmueller/x-ray#98]
I had an error in a Transformer stream that was being piped to from the readable stream generated by .write(). However, it took me some time to figure out where the error was because the process was being exited cleanly and trying to use process.on to catch uncaught exceptions wasn't fixing that. Eventually, I came to realize the error was being squelched by something in xray or one of it's dependencies (e.g. maybe batch). Feel free to let me know if I'm completely off base here.

I've created a [gist](https://gist.github.com/KodeAndGame/469bba3efd9b704cf64b) that shows two examples. App.js starts with xray.write, pipes it to my transform which throws an error and then pipes that to stdout. Process exits and no errors are reported to console. Conversely, alt.js starts with stdin, pipes it to the same transform and then to stdout. Process exits with the exception I threw. 

I did my best to look through lib/walk and batch/index which seem to be the two files where my error gets moved around between callbacks but unfortunately I didn't really get anywhere. I'd be willing to try fixing this in a PR myself if I could be pointed in the right direction but I'm kind of at a loss here. 

Any help is appreciated. Thanks!

**Comment by KodeAndGame** [comment]
This might the be the same as #87. It's not exactly clear.

**Comment by KodeAndGame** [comment]
I had better luck debugging and have updated my gist with a log of my session. Long story short, my error gets passed around a couple times between lib/walk and batch. Presumably this is in order to complete the batch but I still haven't dug in enough to know for sure. 

Finally when batch is done, it doesn't check to see if there's an error, it just exits the function, doing nothing with the error that's been passed around. You can see this in batch/index.js:124. 

My instinct is to stop it somewhere in lib/walk or at least provide a caller (i.e. me) the option to do so but I'm not sure if this is a breaking change for other users of your package. I'm going to do a little more digging and see if I can get a PR in.

**Comment by gebrits** [comment]
@KodeAndGame have you attempted a PR for this? Having the same issue here

**Comment by jonknapp** [comment]
Would we be able to get a new version of the library this with fix pulled in?  Not sure of the state of the other commits since the last release or I'd make the branch myself.

**Comment by DannyCork** [comment]
2.10 25 Mar 2016 contains this, closing.
